MODEL:
  NAME: "segformer_b4"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  NUM_CLASSES: 16
  HYPER: True
  REDUCED_CHANNELS: 64
  HFR: False
DATASETS:
  SOURCE_TRAIN: "synthia_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0,1,2,3,4,5,6,7]
  BASE_LR: 6e-5
  OPTIM: "adam"
  SCHEDULER: "poly"
  WEIGHT_DECAY: 1e-2
  NUM_ITER: 60000
  BATCH_SIZE: 1
  WARMUP_ITERS: 1000
ACTIVE:
  NAME: 'HALO'
  BUDGET: 1.
WANDB:
  ENABLE: True
  PROJECT: 'active_domain_adapt'
  GROUP: 'source_target_synthia'
  ENTITY: 'pinlab-sapienza'
NAME: 'halo_segformer_b4_fully_sup'
resume: 'results/pretrain_synthia/segformer_b4_hyper/model_global_step=13998.0_mIoU=43.90.ckpt'
OUTPUT_DIR: 'results/source_target_synthia/'
PROTOCOL: 'fully_sup'
DEBUG: False
