MODEL:
  NAME: "segformer_b4"   # deeplabv3plus_resnet101
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  HYPER: True
  HFR: False
  REDUCED_CHANNELS: 64
  NUM_CLASSES: 16
DATASETS:
  SOURCE_TRAIN: "synthia_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [4,5,6,7]
  BATCH_SIZE: 2
  BASE_LR: 1e-5
  OPTIM: "adam"
  SCHEDULER: "poly"
  WEIGHT_DECAY: 1e-2
  NUM_ITER: 60000
  WARMUP_ITERS: 1000
WANDB:
  ENABLE: True
  GROUP: 'synthia_pretraining'
  PROJECT: 'active_domain_adapt'
  ENTITY: 'pinlab-sapienza'
NAME: 'segformer_b4_hyper'
OUTPUT_DIR: 'results/pretrain_synthia/'
PROTOCOL: 'source'
