MODEL:
  NAME: "deeplabv2_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 64      # 256 or 10
  HFR: False
DATASETS:
  TEST: "acdc_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [7]
TEST:
  VIZ_SCORE: False
  VIZ_WRONG: False
  SAVE_EMBED: True
  BATCH_SIZE: 1
NAME: 'halo_cs_to_acdc_v2_2perc'
resume: 'results/source_target_acdc/halo_cs_to_acdc_v2_2perc/model_global_step=18998.0_mIoU=63.24.ckpt'
OUTPUT_DIR: 'results/source_target_acdc/'
DEBUG: False
