MODEL:
  NAME: "deeplabv3plus_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 64      # 256 or 10
  HFR: True
DATASETS:
  TEST: "acdc_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0]
TEST:
  VIZ_SCORE: False
  VIZ_WRONG: False
  SAVE_EMBED: True
  BATCH_SIZE: 1
NAME: 'halo_cs_to_acdc_5perc'
resume: 'results/source_target_acdc/halo_cs_to_acdc_5perc/model_global_step=24998.0_mIoU=66.37.ckpt'
OUTPUT_DIR: 'results/source_target_acdc/'
DEBUG: 0